### ISSUE TITLE
Versions later than v0.1 produce a black screen on some hardware

### ISSUE THREAD

**Issue by krisives** [beyretb/AnimalAI-Olympics#20]
After some debugging we have seen an interesting problem and we are curious if you can help us or possibly make a different Unity build that addresses some problems we have. On some configurations we have observed that any version later than v0.1 will produce a consistently black screen right after the Unity logo shows. This includes v0.2, v0.3, v0.4 and v0.5 we have tested.

On real hardware using KDE it runs all versions correctly never producing a black screen.

On VMWare Player and VirtualBox with 3D acceleration enabled or disabled it always produces a black screen when running anything but v0.1. Testing was done both with python and separately with just running the AnimalAI.x86_64 binary manually. This was tested with Ubuntu 18.04.2 LTS, 19.04 as well as KDE Neon User.

Firstly, it seems strange that v0.1 would work and the others wouldn't, which is why we are bothering to report this.

Second, we tested other things made with Unity and games that are more complex than AnimalAI and they work fine.

Here is an attached diff of the output of which OpenGL features are supported, with the red/removed portions being ones that aren't present on the systems where black screens are produced: https://gist.github.com/krisives/84e67c6983c11902c3bbda8cfcf0992e

Lastly, an attempt was made to create a Frankenstein combination of executables and AnimalAI_Data directories that produced results other than black screens. This was "successful" to some degree in that if you take v0.5 files and replace the `AnimalAI_Data/Managed` directory with files from v0.1 it will no longer produce a black screen, but instead produces a bunch of pink missing textures.

Please let us know if you need any additional details or have any suggestions.

**Comment by beyretb** [comment]
Hi Kris,

Thanks a lot for pointing this issue, I've investigated and identified the culprit. It comes from the setup we're using in Unity for rendering and which seems to fail on virtual machines.This setup lowers the rendering quality to improve the speed of the environment. We only released this from 0.2 onward which explains why 0.1 works fine.

The good news is that you still get observations in Python! Therefore you can still train an agent, even though I appreciate that's far from ideal...

I cannot find an easy fix for the issue and will need to have a chat with Unity to see how we can proceed. I will update this thread as soon as I have more news.

Apologies for any inconvenience this may cause, we'll hopefully get it fixed in the next release!

**Comment by miranthajayatilake** [comment]
I'm facing the same issue of a blacked out window, but surprisingly it worked the first few times I opened it. But suddenly stopped rendering the graphics after some time. (I'm trying with env_linux_v0.5)

Hoping to get feedback on this issue soon. 

Many thanks!

**Comment by beyretb** [comment]
Hello,

The issue is still ongoing unfortunately. We have been in touch with Unity (as it seems the problem is independent from the animal AI competition itself), and they are investigating. 

I will let you know as soon as we have some news for you! 

Apologies again for this

Ben

**Comment by krisives** [comment]
Also note that a poor man's solution is to launch another window and copy the observation image buffer over to it, similar to what `visualizeLightsOff.py` does with matpolot

**Comment by krisives** [comment]
Since v0.6.0 this now works in a VM and no longer creates a black screen.
