### ISSUE TITLE
[Question]Disable rendering on Gym Wrapper

### ISSUE THREAD

**Issue by Rowing0914** [beyretb/AnimalAI-Olympics#23]
Hi!

I am delighted to work on this env and thank you for making this!
I have one little Feature request, which is about rendering an Env during training.

As the original ML agent supports the way to disable the rendering of env, I would like to have it on AnimalAI as well because we might want to train the model on a remote server which does not have access to GUI.

Reference: https://github.com/Unity-Technologies/ml-agents/issues/1413

Thanks,

**Comment by krisives** [comment]
From what I can tell they have hard-coded `no_graphics=False` in their version.

**Comment by beyretb** [comment]
Hi,

As @krisives mentioned, you cannot get visual observations if you disable rendering, which is why we set this value to False.

Thankfully, you can still train on the cloud or in a container by starting an X server and running the environment in `xvfb`. You can see how this is done [on AWS here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Training-on-Amazon-Web-Service.md) and [in docker here](https://github.com/Unity-Technologies/ml-agents/blob/master/docs/Using-Docker.md).

Hope this helps

**Comment by Rowing0914** [comment]
Thank you for quick response @krisives , @beyretb !
Yeah,, that's true! we can do that way.

Sorry, I should have mentioned that I assume "train the model in Parallel". For example, unless we don't care about opening multiple windows for training an agent in parallel when we use rollout function to go through an episode several times, we normally use `mpi4py` or `ray` from UCB or other sophisticated libraries, right? In that case, if we can disable the rendering function I thought we could avoid those redundant windows.

**Comment by beyretb** [comment]
Yes you're correct regarding using MPI for training multiple agents in parallel. I'm not sure how opening several windows would impact the performance here, I had a chat with Unity about it at the time they were developing v0.8 of mlagents, and I know this feature was part of the release.
Our implementation is based on their v0.7 so it does not include any performance improvement they have released on that side.

You can still open one environment with several independent agents using `UnityEnvironment` (not Gym), and have as many arena configurations as you want. From the tests I have conducted, this speeds training non linearly (ie: faster to get 4 observations in one environment than 4 environments with one observation each). Training is therefore synchronous though. You can of course still open several environments to use parallel training, it might just be a bit slower.

**Comment by beyretb** [comment]
Hello,

A bit of feedback on this, I've tested adding an extra brain with a camera on top of each arena, and it slows down training significantly! We're talking an order of magnitude slower, this is due to the fact that the resolution of this camera needs to be (much) higher than the agent's, therefore making rendering slower.

We could look into adding it as an optional flag when launching the environment if you think this feature is indispensable. I am also not too keen on adding too many flags like that but could find an alternative maybe. Let me know your thoughts, it would only happen after we launch the competition anyway as it requires quite some additions and testing.

Ben

**Comment by Rowing0914** [comment]
Hello @beyretb 

Thank you for testing the extra feature! As far as our group members discussed, we think this feature is not so urgent for us at least for the meantime so I think it is okay!

Thank you for your responsiveness again!

Best,

**Comment by beyretb** [comment]
closing this issue
