### ISSUE TITLE
v 06 yellow bouncing ball labelled as bad goal

### ISSUE THREAD

**Issue by pnealgit** [beyretb/AnimalAI-Olympics#25]
In the description of objects, the bouncing yellow ball is labelled as bad. Is this correct ?

**Comment by krisives** [comment]
@beyretb should clarify here because the documentation is strange. Almost everything indicates they are *good* goals, such as the name `GoodGoalMulti`, but then this sentence seems out of place:

> A bad reward bouncing on objects. Will start moving in the direction provided by the rotation parameter 

My understanding is that green objects terminate the episode with a good score, red objects terminate an episode with a bad score, and orange/yellow objects accumulate score until either all of them are collected (including a green one if present) or the episode terminates (such as by time, death zone, red ball, etc.)

I'm sure someone more official can clarify or update the documentation.

**Comment by mdcrosby** [comment]
Krisives is correct. I've fixed and clarified the documentation page about rewards. As well as fixing the mistake it should be a bit easier to read now. 

We plan to tidy up the rest of the docs on release.
