### ISSUE TITLE
Training.py gives me runtime warning in playground

### ISSUE THREAD

**Issue by pnealgit** [beyretb/AnimalAI-Olympics#4]
Dear AAO,
I am running 
Mac OS X 10.14.4
Python 3.6.6
numpy '1.14.5'

When I do:
$ python3 train.py

After a few steps during which the little blue guy is running around bumping 
into things, I get the error warning below and then the blue guy doesn't 
run around anymore. 

Any ideas ??

Best 
Phil Neal

curiosity_enc_size:	256
	model_path:	./models/train_example/Learner
INFO:mlagents.envs:Saved Model
INFO:mlagents.trainers: train_example-1: Learner: Step: 1000. No episode was completed since last summary. Training.
INFO:mlagents.envs:Saved Model
INFO:mlagents.trainers: train_example-1: Learner: Step: 2000. No episode was completed since last summary. Training.
/Users/pneal/aao/may2/animalai/trainers/ppo/trainer.py:335: RuntimeWarning: invalid value encountered in subtract
  (advantages - advantages.mean()) / (advantages.std() + 1e-10))
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/_methods.py:112: RuntimeWarning: invalid value encountered in subtract
  x = asanyarray(arr - arrmean)
INFO:mlagents.envs:Saved Model
INFO:mlagents.trainers: train_example-1: Learner: Step: 3000. No episode was completed since last summary. Training.
INFO:mlagents.envs:Saved Model

**Comment by beyretb** [comment]
Hi, 

When training make sure you use a configuration file with a limited number of steps per episode. All environments in the `config` folder are set to `t: 0` which means that episodes only end when a reward is collected (makes it easier to use in play mode). This combined with the current default configuration file that tries to spawn every available object, makes it very unlikely to have a successful training.

I will change the default configuration file for training so that you can actually get a trained agent by simply running `train.py`. I will push this in the coming days.

**Comment by beyretb** [comment]
Closing as v0.2 fixes this issue
