### ISSUE TITLE
Clarifications on categories

### ISSUE THREAD

**Issue by giadefa** [beyretb/AnimalAI-Olympics#48]
I would like to have a clarifications on https://mdcrosby.com/blog/animalaieval.html

Category N1 says "Allowed objects: all goals", as red balls are called badGoals, does it mean that in the first category there can be also red balls? Also the example has 1 green ball, but is this representative of the real distribution in the test? Or there can be 100 green balls?

Category N2 says "Allowed objects: All except zones" does it mean that barriers can be present? If so what is the difference with category N3?

Are there more precisely defined docs?

**Comment by mdcrosby** [comment]
> does it mean that in the first category there can be also red balls?

Correct

> Also the example has 1 green ball, but is this representative of the real distribution in the test?

The examples are not meant to be representative of all tests in a category (just of the kinds of objects involved and the kind of concept). They are just suggestions to get started and to show the syntax of the configuration files. I'll clarify this in the eval post as the information for this has become spread out over multiple sources.

> Category N2 says "Allowed objects: All except zones" does it mean that barriers can be present?

Walls can be present, but not in a way such that information (e.g. goals) is supposed to be concealed behind them. This is mentioned elsewhere, but, again, I'll bring everything together to add some clarity now that the documentation surrounding this has become too spread out. C3 is the first time that rewards begin behind (from the perspective of the agent) any of the immovable objects.

> Are there more precisely defined docs?

As mentioned above, I will collate all the publicly available test information so that it is all in one place. Hopefully this will improve clarity.

**Comment by mdcrosby** [comment]
We've released more information and collated some of the older info. 

See https://www.mdcrosby.com/blog/animalaiprizes1.html
