### ISSUE TITLE
Running the simulation on multicore

### ISSUE THREAD

**Issue by ironbar** [beyretb/AnimalAI-Olympics#49]
Hi, 
Yesterday I started playing with the sample script trainMLAgents.py. I noticed that the simulation is running on a single core. Is there an easy way to make it multicore to speedup training?

Thanks
ironbar

**Comment by beyretb** [comment]
Hello,

To my knowledge Unity manages anything related to computing resources (both CPU and GPU) and I would assume that if only a single core is used it's because only one is needed. Also, the AnimalAI environment doesn't particularly make use of multithreading. 

Have you noticed the environment being a bottleneck?

**Comment by ironbar** [comment]
It seems to be the bottleneck. During train only one core of the cpu is being used and the gpu is almost idle. Even when using a large number of arenas like 36 only one core is used.

**Comment by beyretb** [comment]
I just got confirmation that the base code for ML Agents (which we built on top of) does not use multithreading. The rest of Unity (rendering, physics...) does use it.

I did some tests a few months back for up to 16 agents and it was still faster to have only one environment running rather than several ones. But I guess you might want to try and run some tests yourself if you find a good way to have several instances of the environment running on several cores.
