### ISSUE TITLE
Non PPO/TensorFlow  example

### ISSUE THREAD

**Issue by pnealgit** [beyretb/AnimalAI-Olympics#5]
Would it be possible to have a training example that doesn't use Tensorflow and/or
the Unity reinforcement agents ? 
Something real simple that calls the AnimalAi training environment with a good brain ,
and prints all the observation data of all kinds , visual,text, float.

**Comment by beyretb** [comment]
Hello,

I will add something more user friendly for the actual release at the end of June. I am thinking of writing a couple Jupyter notebooks, is that what you're referring to?

**Comment by pnealgit** [comment]
Hi Benjamin,

Yes. I found a brief python code introduction at:
https://github.com/Unity-Technologies/ml-agents/blob/master/notebooks/getting-started.ipynb

I have been slowly modifying that code to incorporate more AnimalAI
information and tweaking stuff to see what changes.

So something like the above link, but exclusively devoted to the AnimalAi
project
would be great.

Here are some questions:

1. Is the only AnimalAi brain the 'default brain' ?
2. Can I use CSharp instead of python ?
3. Do I have to use the Unity ML-Agents or can I use my own (ie decision
tree, MNB, NEAT, etc)?
4. If I use my own:
   A. How do I integrate it into the AnimalAi environment ? (The train.py
code is a bit dense for me)
   B.  How do I flip it from training back in to inference ?

5. How do I run 'headless' (no imagery just data) ?

Best regards.
Great work.
Phil Neal

**Comment by krisives** [comment]
> Can I use CSharp instead of python ?

So far @beyretb has mentioned that agents will be put into some kind of container (like Docker) at which point as long as you are willing to communicate using the same protocol as the Python code provided, then yes, you can use whatever language you want like C#. However, the official rules haven't been released regarding this yet.

> Do I have to use the Unity ML-Agents or can I use my own (ie decision tree, MNB, NEAT, etc)?

As far as I know you can use whatever AI model you want.

**Comment by beyretb** [comment]
> Is the only AnimalAi brain the 'default brain' ?

I m not sure what you mean by default brain, are you referring to the Unity ML Agent's learning brain? If so then yes there is only a single brain you can use for training. There is a player one that gets switched with the training one in case you run the program in play mode.

> 2. Can I use CSharp instead of python ?

As @krisives mentioned we plan on using containers for submission so you can in theory use various languages. However we only provide the Python API for interfacing with the Unity executable for training. If you wish to use any other language you will have to work on your own communication pipeline.

> 3. Do I have to use the Unity ML-Agents or can I use my own (ie decision
tree, MNB, NEAT, etc)?

Not at all! Any library/algos are welcome

>4. If I use my own:
>   A. How do I integrate it into the AnimalAi environment ? (The train.py
code is a bit dense for me)
>   B.  How do I flip it from training back in to inference ?

As long as you can interface with the compiled environment to send actions and collect observations and rewards, you can implement training and inference however you like. Look at `animalai/envs/environment.py` to understand how communications work in Python.

> 5. How do I run 'headless' (no imagery just data) ?

As we use visual observations (pixels) you cannot run training without rendering the environment (which is why we advise to minimise the Unity window as this speeds up training). You can nonetheless run all training on the cloud.

**Most of the above is subject to change by the end of June when we launch the competition.**

**Comment by beyretb** [comment]
closing this issue as we have now repackaged the environment API and testing in two separate packages.
Jupyter notebooks will comesoon.
