### ISSUE TITLE
Google Colab Run error

### ISSUE THREAD

**Issue by DanielS684** [beyretb/AnimalAI-Olympics#93]
My google colab shows this "UnityTimeOutException: The Unity environment took too long to respond." when I'm trying to run this in google colab. I made sure to start a virtual display before running code so I don't know what the problem is, please help.

[This is the colab I used.](https://colab.research.google.com/drive/1twQlunKN__IWje5lMf0N1PhewPa-lRRX?usp=sharing)

**Comment by beyretb** [comment]
Hi! Appologies for the (very) late response, I was having issues with my github account.

This error is typical of the python side failing to connect to the unity environment either because the latter is unable to launch due to virtual display issues, or it might be the connection between the two failing to establish.
I have never tried to run the environment in a colab and am unsure how this would work. My best advice at the moment would be to take a look at the way it works with ML-Agents, maybe this: https://github.com/Unity-Technologies/ml-agents/issues/2684 ?

I will try to take a look over the weekend!
